export default {
  getListData: getListData,
  getSingleData: getSingleData
}

function getListData() {
  return [  
    {  
      "name":"Arbeiderpartiet",
      "slug":"a",
      "_links":{  
         "self":{  
            "href":"https://www.holderdeord.no/api/parties/a"
         },
         "representatives":{  
            "href":"https://www.holderdeord.no/api/parties/a/representatives"
         },
         "attending_representatives":{  
            "href":"https://www.holderdeord.no/api/parties/a/representatives?attending=true"
         },
         "widget":{  
            "href":"https://www.holderdeord.no/parties/a/widget",
            "type":"text/html"
         },
         "logo":{  
            "href":"https://www.holderdeord.no/api/parties/a/logo{?version}",
            "templated":true,
            "type":"image/png"
         }
      }
    },
    {  
      "name":"Fremskrittspartiet",
      "slug":"frp",
      "_links":{  
         "self":{  
            "href":"https://www.holderdeord.no/api/parties/frp"
         },
         "representatives":{  
            "href":"https://www.holderdeord.no/api/parties/frp/representatives"
         },
         "attending_representatives":{  
            "href":"https://www.holderdeord.no/api/parties/frp/representatives?attending=true"
         },
         "widget":{  
            "href":"https://www.holderdeord.no/parties/frp/widget",
            "type":"text/html"
         },
         "logo":{  
            "href":"https://www.holderdeord.no/api/parties/frp/logo{?version}",
            "templated":true,
            "type":"image/png"
         }
      }
    },
    {  
      "name":"Høyre",
      "slug":"h",
      "_links":{  
         "self":{  
            "href":"https://www.holderdeord.no/api/parties/h"
         },
         "representatives":{  
            "href":"https://www.holderdeord.no/api/parties/h/representatives"
         },
         "attending_representatives":{  
            "href":"https://www.holderdeord.no/api/parties/h/representatives?attending=true"
         },
         "widget":{  
            "href":"https://www.holderdeord.no/parties/h/widget",
            "type":"text/html"
         },
         "logo":{  
            "href":"https://www.holderdeord.no/api/parties/h/logo{?version}",
            "templated":true,
            "type":"image/png"
         }
      }
    },
    {  
      "name":"Kristelig Folkeparti",
      "slug":"krf",
      "_links":{  
         "self":{  
            "href":"https://www.holderdeord.no/api/parties/krf"
         },
         "representatives":{  
            "href":"https://www.holderdeord.no/api/parties/krf/representatives"
         },
         "attending_representatives":{  
            "href":"https://www.holderdeord.no/api/parties/krf/representatives?attending=true"
         },
         "widget":{  
            "href":"https://www.holderdeord.no/parties/krf/widget",
            "type":"text/html"
         },
         "logo":{  
            "href":"https://www.holderdeord.no/api/parties/krf/logo{?version}",
            "templated":true,
            "type":"image/png"
         }
      }
    },
    {  
      "name":"Miljøpartiet De Grønne",
      "slug":"mdg",
      "_links":{  
         "self":{  
            "href":"https://www.holderdeord.no/api/parties/mdg"
         },
         "representatives":{  
            "href":"https://www.holderdeord.no/api/parties/mdg/representatives"
         },
         "attending_representatives":{  
            "href":"https://www.holderdeord.no/api/parties/mdg/representatives?attending=true"
         },
         "widget":{  
            "href":"https://www.holderdeord.no/parties/mdg/widget",
            "type":"text/html"
         },
         "logo":{  
            "href":"https://www.holderdeord.no/api/parties/mdg/logo{?version}",
            "templated":true,
            "type":"image/png"
         }
      }
    },
    {  
      "name":"Senterpartiet",
      "slug":"sp",
      "_links":{  
         "self":{  
            "href":"https://www.holderdeord.no/api/parties/sp"
         },
         "representatives":{  
            "href":"https://www.holderdeord.no/api/parties/sp/representatives"
         },
         "attending_representatives":{  
            "href":"https://www.holderdeord.no/api/parties/sp/representatives?attending=true"
         },
         "widget":{  
            "href":"https://www.holderdeord.no/parties/sp/widget",
            "type":"text/html"
         },
         "logo":{  
            "href":"https://www.holderdeord.no/api/parties/sp/logo{?version}",
            "templated":true,
            "type":"image/png"
         }
      }
    },
    {  
      "name":"Sosialistisk Venstreparti",
      "slug":"sv",
      "_links":{  
         "self":{  
            "href":"https://www.holderdeord.no/api/parties/sv"
         },
         "representatives":{  
            "href":"https://www.holderdeord.no/api/parties/sv/representatives"
         },
         "attending_representatives":{  
            "href":"https://www.holderdeord.no/api/parties/sv/representatives?attending=true"
         },
         "widget":{  
            "href":"https://www.holderdeord.no/parties/sv/widget",
            "type":"text/html"
         },
         "logo":{  
            "href":"https://www.holderdeord.no/api/parties/sv/logo{?version}",
            "templated":true,
            "type":"image/png"
         }
      }
    },
    {  
      "name":"Venstre",
      "slug":"v",
      "_links":{  
         "self":{  
            "href":"https://www.holderdeord.no/api/parties/v"
         },
         "representatives":{  
            "href":"https://www.holderdeord.no/api/parties/v/representatives"
         },
         "attending_representatives":{  
            "href":"https://www.holderdeord.no/api/parties/v/representatives?attending=true"
         },
         "widget":{  
            "href":"https://www.holderdeord.no/parties/v/widget",
            "type":"text/html"
         },
         "logo":{  
            "href":"https://www.holderdeord.no/api/parties/v/logo{?version}",
            "templated":true,
            "type":"image/png"
         }
      }
    }
  ];
}

function getSingleData() {
  return {  
    "name":"Arbeiderpartiet",
    "slug":"a",
    "_links":{  
       "self":{  
          "href":"https://www.holderdeord.no/api/parties/a"
       },
       "representatives":{  
          "href":"https://www.holderdeord.no/api/parties/a/representatives"
       },
       "attending_representatives":{  
          "href":"https://www.holderdeord.no/api/parties/a/representatives?attending=true"
       },
       "widget":{  
          "href":"https://www.holderdeord.no/parties/a/widget",
          "type":"text/html"
       },
       "logo":{  
          "href":"https://www.holderdeord.no/api/parties/a/logo{?version}",
          "templated":true,
          "type":"image/png"
       }
    }
  };
}